/** Normalize URL slug segment for paths */
export function normalizeSlug(slug: string): string {
  return slug
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-|-$/g, "");
}

/** Default apply link for a program (consultation form with program pre-selected) */
export function buildProgramCtaLink(slug: string): string {
  const s = normalizeSlug(slug);
  return s ? `/consultation?program=${s}` : "/consultation";
}

/** Use custom CTA when provided; otherwise generate from program slug */
export function normalizeProgramCtaLink(slug: string, ctaLink?: string | null): string {
  const trimmed = ctaLink?.trim();
  if (trimmed) return trimmed;
  return buildProgramCtaLink(slug);
}

/** Announcement banner link — blank falls back to a sensible site page */
export function normalizeAnnouncementLink(
  link?: string | null,
  options?: { type?: "promo" | "service" | "notice" }
): string | null {
  const trimmed = link?.trim();
  if (trimmed) return trimmed;

  switch (options?.type) {
    case "service":
      return "/services";
    case "promo":
      return "/programs";
    case "notice":
      return "/contact";
    default:
      return "/consultation";
  }
}

/** True if CTA matches auto-generated pattern for this slug (safe to refresh on slug change) */
export function isAutoGeneratedProgramCta(slug: string, ctaLink?: string | null): boolean {
  const trimmed = ctaLink?.trim();
  if (!trimmed) return true;
  const expected = buildProgramCtaLink(slug);
  return trimmed === expected || trimmed === "/consultation";
}
